# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy API to Azure Web App - vulnex

on:
  push:
    branches:
      - main
    paths:
      - "api/**" # Only trigger when changes are in the api/ directory
  workflow_dispatch:

jobs:
  deploy: # Renamed the job to 'deploy' as it now handles everything
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Install dependencies (Root Workspace)
        run: npm install

      - name: "Deploy to Azure Web App and set Startup Command"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "vulnex"
          slot-name: "Production"
          package: . # Deploy the contents of the root directory
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_84CF847B4D044C819796EAC247E6948A }}
          # Specifies the command Azure will use to start the application
          startup-command: "npm run start:api"
